

function print_header(fid, option)

fprintf(fid, '\n');
fprintf(fid, '*****        generated by ped-ibd        *****\n');
fprintf(fid, '*****        %s        *****\n\n', datestr(now));
fprintf(fid, '\n');

end


